# Generated by Django 4.2.4 on 2023-09-14 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100, null=True)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('inStock', models.BooleanField()),
                ('Images_URL', models.TextField()),
                ('mainImage', models.TextField()),
                ('quantity', models.FloatField()),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ecommerceApp.customer')),
                ('productid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ecommerceApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='productid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ecommerceApp.product'),
        ),
    ]
