# Generated by Django 4.2.4 on 2023-09-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0002_alter_customer_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='productid',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
