# Generated by Django 4.2.4 on 2023-09-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0003_remove_customer_productid_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='mainImage',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
